### ISSUE TITLE
Document the usage by from-ambari and from-source

### ISSUE THREAD

**Issue by liuml07** [Sherry302/caochong#3]
- From ambari can refer to the web page: [https://cwiki.apache.org/confluence/display/AMBARI/Quick+Start+Guide](https://cwiki.apache.org/confluence/display/AMBARI/Quick+Start+Guide)
- From source can use the current usage section, with more details provided, e.g. users has to set the hadoop/spark source directory before running the `run.sh`.

**Comment by weiqingy** [comment]
@liuml07 Could you please help to review the readme? Thanks.

**Comment by liuml07** [comment]
I slightly revised the usage section. Thanks for the contribution!
